version: '2'
services:
    db:
        image: mysql:5.7
        volumes:
            - wp_pusher_db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: esthex_dev
            MYSQL_DATABASE: esthex_dev    
        networks:
            new:
                aliases:
                    - db
            legacy:
                aliases:
                    - mysql      
    wordpress:
        build: ./
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "8080:80"
        networks:
            - legacy
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        networks:
            - new
        ports:
            - 8181:80
        environment:
            PMA_USER: root
            PMA_PASSWORD: esthex_dev     
volumes:
    wp_pusher_db_data:
networks:
    new:
    legacy: